### ISSUE TITLE
IR and Red values listed as HR and SPO2

### ISSUE THREAD

**Issue by adamrenner** [kontakt/MAX30100#1]
The library is parsing the FIFO into HR and SPO2 variables, but I believe that this should be IR and Red absorption values. I don't believe the MAX30100 can compute HR or SPO2 on its own.

**Comment by kontakt** [comment]
That's a fair point, they are only absorption values. I'll change the naming.

**Comment by kontakt** [comment]
Values are now "IR" and "RED" for better clarity.
