### ISSUE TITLE
Red LED values always 0

### ISSUE THREAD

**Issue by adamrenner** [kontakt/MAX30100#2]
I get readings on the IR that look good, but my Red value is consistently 0. Maybe this is a code issue but it could also be a bad connection to the Red Cathode on my PCB.

**Comment by kontakt** [comment]
Did you enable the red led? I have it set to off by default. Check what values your constructor is using.

**Comment by adamrenner** [comment]
I see now.
I turned on SPO2 and the Red LED and everything works now.

**Comment by kontakt** [comment]
Great! Glad it's functioning. If you write up code for SPO2 calculation that's good enough to be an example feel free to submit a pull request; I don't have time to work with that side of the chip.
